---
title: "Covid Data Analysis"
author: "pablo"
date: "4/29/2023"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing the Data

We read the data directly from the below URL, ad display the frist rows to get an idea of the schema. 

```{r }
library(tidyverse)
pth<-"https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"

filenames<-c("time_series_covid19_confirmed_US.csv",  "time_series_covid19_confirmed_global.csv", "time_series_covid19_deaths_US.csv",  "time_series_covid19_deaths_global.csv")

#Read Files from URL
us_cases<-read_csv(paste(pth,filenames[1],sep=''))
global_cases<-read_csv(paste(pth,filenames[2],sep=''))
us_deaths<-read_csv(paste(pth,filenames[3],sep=''))
global_deaths<-read_csv(paste(pth,filenames[4],sep=''))

# Transpose Global Cases
global_cases <- global_cases %>%
  pivot_longer(cols=-c('Province/State','Country/Region','Lat','Long'),
               names_to='date',
               values_to='cases') %>%
  select(-c('Lat','Long'))

#Transpose Global Deaths
global_deaths <- global_deaths %>%
  pivot_longer(cols=-c('Province/State','Country/Region','Lat','Long'),
               names_to='date',
               values_to='deaths') %>%
  select(-c('Lat','Long'))

#Merge Global Cases and Deaths
global <- global_cases %>%
  full_join(global_deaths) %>%
  rename(Country_Region=`Country/Region`,
         Province_State= `Province/State`) %>%
  mutate(date=mdy(date))



#Transpose US cases
us_cases <- us_cases %>%
  pivot_longer(cols=-c(UID:Combined_Key),
               names_to='date',
               values_to='cases') %>%
  select(Admin2:cases) %>% 
  mutate(date=mdy(date)) %>%
  select(-c(Lat,Long_))
head(us_cases)

#Transpose US deaths
head(us_deaths)
us_deaths <- us_deaths %>%
  pivot_longer(cols=-c(UID:Population),
               names_to='date',
               values_to='deaths') %>%
  select(Admin2:deaths) %>% 
  mutate(date=mdy(date)) %>%
  select(-c(Lat,Long_))
head(us_deaths)

#Merge US cases and deaths
us<-us_cases %>%
  full_join(us_deaths)
head(us)

#Create a combined key for global
global <- global %>%
  unite("Combined_Key",
        c(Province_State,Country_Region),
        sep=",",
        na.rm=TRUE,
        remove= FALSE)
#Import Population
uid<-read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv") %>%
  select(-c(Lat, Long_,Combined_Key,code3,iso2,iso3,Admin2))
head(uid)

global<-global %>%
  left_join(uid,by=c('Province_State','Country_Region')) %>%
  select(-c(UID,FIPS)) %>%
  select(c(Province_State,Country_Region,date, cases,deaths,Population,Combined_Key))

head(global)
```


## Visualization 

```{r, echo=FALSE}
US_by_state <- us %>%
  group_by(Province_State,Country_Region,date) %>%
  summarize(cases =sum(cases), deaths=sum(deaths), Population=sum(Population)) %>%
  mutate(deaths_per_mill = deaths*1e6/Population) %>%
  select(Province_State, Country_Region, date, cases,deaths,deaths_per_mill,Population) %>%
  ungroup()

head(US_by_state)
```

```{r, echo=FALSE}
US_totals <- US_by_state %>%
  group_by(Country_Region,date) %>%
    summarize(cases =sum(cases), deaths=sum(deaths), Population=sum(Population)) %>%
  mutate(deaths_per_mill = deaths*1e6/Population) %>%
  select(Country_Region, date, cases,deaths,deaths_per_mill,Population) %>%
  ungroup()
head(US_totals)
```


Let's see the cumulative Covid Cases and Deaths in the US through time
```{r, echo=FALSE}
US_totals %>%
  filter(cases>0) %>%
  ggplot(aes(x=date,y=cases))+
  geom_line(aes(color="cases"))+
  geom_point(aes(color="cases"))+
  geom_line(aes(y=deaths, color="deaths"))+
  geom_point(aes(y=deaths, color="deaths"))+
  scale_y_log10()+
  theme(legend.position = "bottom",
        axis.text.x=element_text(angle=90)) +
  labs(title= "Covid19 in the US", y=NULL)

```



Now, for a specific state, lets say New Jersey

```{r, echo=FALSE}
state<- "New Jersey"
US_by_state %>%
  filter(Province_State==state)%>%
  filter(cases>0) %>%
  ggplot(aes(x=date,y=cases))+
  geom_line(aes(color="cases"))+
  geom_point(aes(color="cases"))+
  geom_line(aes(y=deaths, color="deaths"))+
  geom_point(aes(y=deaths, color="deaths"))+
  scale_y_log10()+
  theme(legend.position = "bottom",
        axis.text.x=element_text(angle=90)) +
  labs(title= str_c("Covid19 in ",state), y=NULL)

```


#Model: 